import type { Metadata } from 'next';
import { ReactNode } from 'react';
import Providers from '@/providers';

export const metadata: Metadata = {
  title: 'Dokan Abdo',
  description: 'Generated by create next app',
  icons: {
    icon: '/image/logo.png',
  },
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps): React.JSX.Element {
  return (
    <html lang="en">
      <head />
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}

